
@Host= http://localhost:7000
@urlClient=/api/client 
@urlHotel=/api/hotel
@urlTrip=/api/trip 
########
### 
GET {{Host}}{{urlClient}}
###
GET {{Host}}{{urlClient}}/23

### 
GET {{Host}}{{urlHotel}}
###
GET {{Host}}{{urlHotel}}/5

### 
GET {{Host}}{{urlTrip}}
###
GET {{Host}}{{urlTrip}}/6